### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by pmadar** [tigranbs/proxy-render#1]
Hi,
I tried to proxy my rails server. 
I made a POST request to my AppRouter.js proxy server like that: 
```
def my_route
  http = Net::HTTP.new('localhost', '3004')
  request = Net::HTTP::Post.new('/AppRouter.js', {'Content-Type' => 'application/json'})
  request.body = { }.to_json
  raw_html = http.request(request)
  render :inline => raw_html
end
```
And i am getting error in proxy server:
```
Proxy Render Running on port 3004!
/Users/pavolmadar/www/fantasy-game/client/assets/javascripts/AppRouter.js:2
import React, { Component, PropTypes } from 'react'
^^^^^^
SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:511:25)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at fs.stat.e (/Users/pavolmadar/.nvm/versions/node/v6.0.0/lib/node_modules/proxy-render/server.js:44:19)
    at FSReqWrap.oncomplete (fs.js:117:15)
```
I ran proxe server with command: 
```
pxrepxrender -p 3004 ./client/assets/javascripts

**Comment by tigranbs** [comment]
Hi @pmadar , thanks for detailed explanation.
This is happening because proxy-render loading `babel for jsx` files, and if file extension is `.js` it would be loaded without `babel`.
I'll fix this, so that both `.js and .jsx` files would be loaded by babel.
